compiler:
    solc:
        version: null
        remappings: null

dependencies: null

reports:
# that's does not work, so I have specified each contract manually below
    exclude_paths:
        
    exclude_contracts: 
    - "MockNFT" 
    only_include_project: true